/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.w_ave;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Bykov_SP
 */
public class CNCFrame extends javax.swing.JFrame{

//    JInternalFrame toolOffsetFrame;
//    JInternalFrame mainInnerFrame, programFrame, wrkOffsetFrame;
    
    /**
     * Creates new form ParentJFrame
     */
    public CNCFrame() {
//        initComponents();
        super("SimpleMDI");
        setSize(500, 400);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
//        setLayout(new BorderLayout());
//        JPanel downPanel = new JPanel();
//        
//        JButton mainFrameButton = new JButton("CNC");
//        mainFrameButton.addActionListener(new ActionListener() {
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                mainInnerFrame.moveToFront();
//            }
//        });
//              
//        downPanel.add(mainFrameButton);
//        
//        JButton programButton = new JButton("Progs");
//        programButton.addActionListener(new ActionListener() {
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                programFrame.moveToFront();
//            }
//        });
//        
//        downPanel.add(programButton);
//        
//        JButton toolOffsetButton = new JButton("tool offset");
//        toolOffsetButton.addActionListener(new ActionListener() {
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                toolOffsetFrame.moveToFront();
//            }
//        });
//        downPanel.add(toolOffsetButton);
//        
//        JButton wrkOffsetButton = new JButton("wrk offset");
//        wrkOffsetButton.addActionListener(new ActionListener() {
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                wrkOffsetFrame.moveToFront();
//            }
//        });
//        downPanel.add(wrkOffsetButton);
//        
//        add(downPanel, BorderLayout.SOUTH);
//        // создаем рабочий стол Swing
//        JDesktopPane desktopPane = new JDesktopPane();
//
//        // добавляем его в центр окна
//        add(desktopPane);
//
//        // создаем несколько внутренних окон, применяя доступные конструкторы
//        mainInnerFrame = new JInternalFrame("CNC", false);
//        mainInnerFrame.setLayout(new BorderLayout());
//        
//        toolOffsetFrame = new JInternalFrame("tool offset");
//        programFrame = new JInternalFrame("Programs");
//        wrkOffsetFrame = new JInternalFrame("wrk offset");
//
//        // добавляем внутренние окна на рабочий стол
//        desktopPane.add(toolOffsetFrame);
//        desktopPane.add(programFrame);
//        desktopPane.add(wrkOffsetFrame);
//        desktopPane.add(mainInnerFrame);
//
//        // задаем размеры и расположения, делаем окна видимыми
//        mainInnerFrame.setSize(490, 310);
//        mainInnerFrame.setLocation(0, 0);
//        
//        toolOffsetFrame.setSize(490, 310);
//        toolOffsetFrame.setLocation(0, 0);
//        
//        programFrame.setSize(490, 310);
//        programFrame.setLocation(0, 0);
//        
//        wrkOffsetFrame.setSize(490, 310);
//        wrkOffsetFrame.setLocation(0, 0);
//        
//        //remove the listeners from UI which make the frame move
//        BasicInternalFrameUI basicInternalFrameUI = ((javax.swing.plaf.basic.BasicInternalFrameUI) mainInnerFrame.getUI());
//            for (MouseListener listener : basicInternalFrameUI.getNorthPane().getMouseListeners()) {
//                basicInternalFrameUI.getNorthPane().removeMouseListener(listener);
//            }     
//        mainInnerFrame.setVisible(true);
//        toolOffsetFrame.setVisible(true);
//        programFrame.setVisible(true);
//        wrkOffsetFrame.setVisible(true);
//        mainInnerFrame.moveToFront();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mainFrameButton = new javax.swing.JButton();
        programButton = new javax.swing.JButton();
        toolsOffsetButton = new javax.swing.JButton();
        wrkOffsetButton = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        mainInnerFrame = new javax.swing.JInternalFrame("CNC");
        gCodeListScroll = new javax.swing.JScrollPane();
        gCodeList = new javax.swing.JList();
        programFrame = new javax.swing.JInternalFrame("Programs");
        toolsOffsetFrame = new javax.swing.JInternalFrame("tools offset");
        wrkOffsetFrame = new javax.swing.JInternalFrame("wrk offset");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CNC_Experience");
        setAutoRequestFocus(false);
        setResizable(false);

        mainFrameButton.setText("CNC");
        mainFrameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainFrameButtonActionPerformed(evt);
            }
        });

        programButton.setText("Programs");
        programButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programButtonActionPerformed(evt);
            }
        });

        toolsOffsetButton.setText("tools offset");
        toolsOffsetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toolsOffsetButtonActionPerformed(evt);
            }
        });

        wrkOffsetButton.setText("wrk offset");
        wrkOffsetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrkOffsetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mainFrameButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(programButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolsOffsetButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wrkOffsetButton)
                .addGap(0, 402, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainFrameButton)
                    .addComponent(programButton)
                    .addComponent(toolsOffsetButton)
                    .addComponent(wrkOffsetButton))
                .addContainerGap())
        );

        mainInnerFrame.setVisible(true);

        gCodeList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "x-1. y5.", "x3. y0.", "x10." };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        gCodeListScroll.setViewportView(gCodeList);

        javax.swing.GroupLayout mainInnerFrameLayout = new javax.swing.GroupLayout(mainInnerFrame.getContentPane());
        mainInnerFrame.getContentPane().setLayout(mainInnerFrameLayout);
        mainInnerFrameLayout.setHorizontalGroup(
            mainInnerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainInnerFrameLayout.createSequentialGroup()
                .addComponent(gCodeListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainInnerFrameLayout.setVerticalGroup(
            mainInnerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainInnerFrameLayout.createSequentialGroup()
                .addGap(0, 160, Short.MAX_VALUE)
                .addComponent(gCodeListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        programFrame.setVisible(true);

        javax.swing.GroupLayout programFrameLayout = new javax.swing.GroupLayout(programFrame.getContentPane());
        programFrame.getContentPane().setLayout(programFrameLayout);
        programFrameLayout.setHorizontalGroup(
            programFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        programFrameLayout.setVerticalGroup(
            programFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        toolsOffsetFrame.setVisible(true);

        javax.swing.GroupLayout toolsOffsetFrameLayout = new javax.swing.GroupLayout(toolsOffsetFrame.getContentPane());
        toolsOffsetFrame.getContentPane().setLayout(toolsOffsetFrameLayout);
        toolsOffsetFrameLayout.setHorizontalGroup(
            toolsOffsetFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        toolsOffsetFrameLayout.setVerticalGroup(
            toolsOffsetFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        wrkOffsetFrame.setVisible(true);

        javax.swing.GroupLayout wrkOffsetFrameLayout = new javax.swing.GroupLayout(wrkOffsetFrame.getContentPane());
        wrkOffsetFrame.getContentPane().setLayout(wrkOffsetFrameLayout);
        wrkOffsetFrameLayout.setHorizontalGroup(
            wrkOffsetFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        wrkOffsetFrameLayout.setVerticalGroup(
            wrkOffsetFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 397, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(programFrame, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainInnerFrame, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(toolsOffsetFrame, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(wrkOffsetFrame, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(programFrame)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(mainInnerFrame, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(toolsOffsetFrame, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(wrkOffsetFrame))
        );
        jDesktopPane1.setLayer(mainInnerFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(programFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(toolsOffsetFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(wrkOffsetFrame, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mainFrameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainFrameButtonActionPerformed
        mainInnerFrame.moveToFront();
    }//GEN-LAST:event_mainFrameButtonActionPerformed

    private void programButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programButtonActionPerformed
        programFrame.moveToFront();
    }//GEN-LAST:event_programButtonActionPerformed

    private void toolsOffsetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toolsOffsetButtonActionPerformed
        toolsOffsetFrame.moveToFront();
    }//GEN-LAST:event_toolsOffsetButtonActionPerformed

    private void wrkOffsetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrkOffsetButtonActionPerformed
        wrkOffsetFrame.moveToFront();
    }//GEN-LAST:event_wrkOffsetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
//    private void wrkOffsetButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
//        CommPortSender.send(new ProtocolImpl().getMessage("g"));
//    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CNCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CNCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CNCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CNCFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CNCFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList gCodeList;
    private javax.swing.JScrollPane gCodeListScroll;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainFrameButton;
    private javax.swing.JInternalFrame mainInnerFrame;
    private javax.swing.JButton programButton;
    private javax.swing.JInternalFrame programFrame;
    private javax.swing.JButton toolsOffsetButton;
    private javax.swing.JInternalFrame toolsOffsetFrame;
    private javax.swing.JButton wrkOffsetButton;
    private javax.swing.JInternalFrame wrkOffsetFrame;
    // End of variables declaration//GEN-END:variables

}
